# 异常

## 异常关键字

**try catch finally throw throws**

try：相当于监控器，监控这串代码有没有报错；

catch：相当于当上面的代码报错时，应该怎么处理；**必须要**

finally：可以不打，但是必须执行，用于善后；

throw；用于抛出异常；

throws：用于方法上面的异常；

```java
   public static void main(String[] args) {
       int a=10;
       int b=0;
        try {
            if(b==0){
                throw new ArithmeticException();//throw 主动抛出异常
            }
            System.out.println(a/b);
        } catch (Exception e) {//catch必须要      用于处理报错后需要怎么处理
            System.out.println("b不能等于为0");
        } finally {
            System.out.println("用于善后");
        }

    }
}
```

```java
  public static void main(String[] args) {
        try {
            new Demo().test01(1, 0);
        } catch (ArithmeticException e) {
            e.printStackTrace();
            System.out.println("b不能为0");
        }
    }


    public void test01(int a,int b)throws ArithmeticException{
        if(b==0){
            throw new ArithmeticException();
        }
    }
```

